// Listar todos los productoc con paginacion
GET http://localhost:3000/api/products/searchproducts?size=20

###

//Guardar producto
POST http://localhost:3000/api/products/newproduct
Content-Type: application/json

{
    "productBarCode": "006",
    "productName": "Azucar",
    "productDescription": "Pa podrir dientes",
    "price": "2900",
    "storage": "115"
}

###

//Consulta dato por barcode
POST    http://localhost:3000/api/products/findproduct
Content-Type: application/json

{
    "productBarCode": "006"
}


###

//elimina dato por id
DELETE http://localhost:3000/api/products/deleteproduct/6178690b4f3372da637d62e1

###
//Actualizar Producto por id
PUT  http://localhost:3000/api/products/updateproduct/617873fc5f070df0eed76499
Content-Type: application/json

{
    "productBarCode": "006",
    "productName": "Azucar",
    "productDescription": "Pa endulzar la vida",
    "price": "2900",
    "storage": "115"
}