//Rest Client
###

//Consultar todos
GET http://localhost:3000/api/tasks

###


//Guardar usuario
POST http://localhost:3000/api/tasks
Content-Type: application/json

{   
    "email": "sol@api.com",
    "password": "202311",
    "profile": "true"
}

###

//Consulta un unico dato por id //
GET http://localhost:3000/api/tasks/6148e30bd511b0d26362ee4f


###

//Consulta dato por email
POST  http://localhost:3000/api/tasks/login

{   
    "email": "Daniel@mongo.com"
}
###

//elimina dato por id
DELETE http://localhost:3000/api/tasks/6148fd162ce07d16c26ea319

###

//Consulta todos los usuarios con perfil true
GET http://localhost:3000/api/tasks/profile


###
//Actualizar usuario
PUT  http://localhost:3000/api/tasks/6148fe1840777134d6bf90c5
Content-Type: application/json

{
    "password": "999999"
}
