//Rest Client
###

//Consultar todos
GET http://localhost:3000/api/users?size=20

###

//Consultar todos Con limites a travez de la url
GET http://localhost:3000/api/users?page=1&size=4

###


//Guardar usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{   
    "email": "juliana@api.com",
    "password": "123456789",
    "profile": "true"
}

###

//Consulta un unico dato por id //
POST http://localhost:3000/api/users/user
Content-Type: application/json

{
    "_id": "6149e19015bcf9c2623ffdce"
}

###

//Consulta dato por email
POST    http://localhost:3000/api/users/login
Content-Type: application/json

{   
    "email": "juliana@api.com"
}
###

//elimina dato por id
DELETE http://localhost:3000/api/users/61572913af3090dca3e98fa0

###

//Consulta todos los usuarios con perfil true
GET http://localhost:3000/api/users/profile


###
//Actualizar usuario
PUT  http://localhost:3000/api/users/6148e815a86a82d9b2d1fca2
Content-Type: application/json

{   "email": "sola@api.com",
    "password": "123456789",
    "profile": "true"
}
