//Rest Client
###

//Consultar todos
GET http://localhost:3000/api/users?size=20

###

//Consultar todos Con limites a travez de la url
GET http://localhost:3000/api/users?page=1&size=4

###


//Guardar usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{   "name": "juan ca galindo",
    "email": "juan@api.com",
    "country": "Colombia",
    "city": "Medellin",
    "password": "0123456789",
    "profile": "",
    "shopName": ""
}

###

//Consulta dato por email
POST    http://localhost:3000/api/users/login
Content-Type: application/json

{   
    "email": "sol@api.com"
}
###

//elimina dato por id
DELETE http://localhost:3000/api/users/617c9c69da369aa90384f6f3

###



//Consulta todos los usuarios con perfil true
GET http://localhost:3000/api/users/sellerprofile


###
//Actualizar usuario
PUT  http://localhost:3000/api/users/update/6179524b1e283ab182355c6e
Content-Type: application/json

{   "email": "sol@api.com",
    "password": "20202020",
    "city": "Bogota",
    "profile": "false"
}
